#!/usr/bin/env bash
#
#  ┌─────────────────────────────────────────────┐
#  │   Dwarf Fortress — macOS Installer          │
#  │   Steam Premium graphics + audio + DFHack   │
#  └─────────────────────────────────────────────┘
#
#  Requirements:
#    · macOS 12+
#    · Homebrew  (https://brew.sh)
#    · Whisky    (https://github.com/Whisky-App/Whisky/releases)
#    · Steam account that owns Dwarf Fortress
#
VERSION="1.0.0"

# Quick help / version — used by Homebrew test block and curious users
if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
    echo "df-setup $VERSION — Dwarf Fortress macOS installer"
    echo "Usage: df-setup [INSTALL_DIR=~/dwarf_fortress]"
    echo "  Installs DF with Steam Premium graphics, audio, and DFHack."
    echo "  Requires: Homebrew, Whisky, Steam account that owns Dwarf Fortress."
    exit 0
fi
if [[ "${1:-}" == "--version" ]]; then
    echo "$VERSION"; exit 0
fi

set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────────────
INSTALL_DIR="${INSTALL_DIR:-$HOME/dwarf_fortress}"
GAME_DIR="$INSTALL_DIR/game"
WINE_DIR="$INSTALL_DIR/wine"
APP_PATH="$HOME/Applications/Dwarf Fortress.app"

DF_VERSION="53_16"
DF_CLASSIC_URL="https://www.bay12games.com/dwarves/df_${DF_VERSION}_win.zip"
DFHACK_VERSION="53.16-r1.1"
DFHACK_URL="https://github.com/DFHack/dfhack/releases/download/${DFHACK_VERSION}/dfhack-${DFHACK_VERSION}-Windows-64bit.zip"

STEAM_APP_ID="975370"
DEPOT_SHARED="975371"    # graphics + audio  (~1 GB)
DEPOT_WINDOWS="975372"   # Windows binary    (~50 MB)

TOTAL_STEPS=10

# ── Colours ───────────────────────────────────────────────────────────────────
R=$'\033[0;31m' G=$'\033[0;32m' Y=$'\033[1;33m'
B=$'\033[0;34m' C=$'\033[0;36m' BOLD=$'\033[1m' NC=$'\033[0m'

step()  { printf "\n${BOLD}${B}[%d/%d]${NC} ${BOLD}%s${NC}\n" "$1" "$TOTAL_STEPS" "$2"; }
ok()    { printf "  ${G}✓${NC} %s\n" "$1"; }
info()  { printf "  ${C}→${NC} %s\n" "$1"; }
warn()  { printf "  ${Y}!${NC} %s\n" "$1"; }
die()   { printf "\n${R}✗ ERROR:${NC} %s\n\n" "$1" >&2; exit 1; }

# ── Embedded DLL stubs (mingw-w64, -nostdlib, kernel32 only) ─────────────────
# msvcp140_atomic_wait.dll — implements all 8 functions DF Steam binary needs
MSVCP140_B64="TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAAZIYGALQ8pWoAEAAAkAAAAPAAJiILAgIvAAIAAAAKAAAAAAAAABAAAAAQAAAAAFxLAwAAAAAQAAAAAgAABAAAAAAAAAAFAAIAAAAAAABwAAAABAAARMQAAAMAYAEAACAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAAAAQAAAAAFAAAI8BAAAAYAAAJAEAAAAAAAAAAAAAADAAAGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWGAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAudGV4dAAAAGABAAAAEAAAAAIAAAAEAAAAAAAAAAAAAAAAAAAgAABgLnJkYXRhAABAAAAAACAAAAACAAAABgAAAAAAAAAAAAAAAAAAQAAAQC5wZGF0YQAAbAAAAAAwAAAAAgAAAAgAAAAAAAAAAAAAAAAAAEAAAEAueGRhdGEAAGAAAAAAQAAAAAIAAAAKAAAAAAAAAAAAAAAAAABAAABALmVkYXRhAACPAQAAAFAAAAACAAAADAAAAAAAAAAAAAAAAAAAQAAAQC5pZGF0YQAAJAEAAABgAAAAAgAAAA4AAAAAAAAAAAAAAAAAAEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFVIieVIiU0QiVUYTIlFILgBAAAAXcNVSInlSIlNEEiJVRhMiUUgRIlNKJBdw1VIieVIiU0QkF3DVUiJ5UiD7GBIjUXASInB6PQAAACLRdRIg8RgXcNVSInlSIPsIEiJTRBIiVUYTIlFIEiLTSBIi1UYSItFEEmJyEiJwejIAAAASIPEIF3DVUiJ5UiD7CBIiU0QSItFEEiJweiaAAAAkEiDxCBdw1VIieVIg+wwSIlNEEiJVRhIx0X4AAAAAOsRSItFEEiJwehtAAAASINF+AFIi0X4SDtFGHLlkJBIg8QwXcNVSInlSIPsIEiJTRBIi0UQSInB6FYAAACQSIPEIF3DVUiJ5UiD7CBIiU0QiVUYi1UYSItFEEiJwegRAAAAkEiDxCBdw5CQkJCQkJCQkJD/JUJPAACQkP8lMk8AAJCQ/yUiTwAAkJD/JRJPAACQkP8lAk8AAJCQDx+EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAR0NDOiAoR05VKSAxNi4yLjAAAAAAAAAAAAAAAAAAAAD//////////wAAAAAAAAAA//////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAFhAAAABAAAAWEAAALRAAAAhAAAAtEAAAOBAAABBAAAA4EAAAVRAAABhAAABVEAAAhhAAACRAAACGEAAApRAAADBAAAClEAAA4hAAADxAAADiEAAAAREAAEhAAAABEQAAJhEAAFRAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEEAgUEAwFQAQQCBQQDAVABBAIFBAMBUAEIAwUIsgQDAVAAAAEIAwUIMgQDAVAAAAEIAwUIMgQDAVAAAAEIAwUIUgQDAVAAAAEIAwUIMgQDAVAAAAEIAwUIMgQDAVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALQ8pWoAAAAAeFAAAAEAAAAIAAAACAAAAChQAABIUAAAaFAAAC0QAAAWEAAApRAAAOIQAABVEAAAOBAAAIYQAAABEQAAkVAAALBQAADJUAAA61AAAAdRAAAkUQAASVEAAGZRAAAAAAEAAgADAAQABQAGAAcAbXN2Y3AxNDBfYXRvbWljX3dhaXQuZGxsAF9fc3RkX2F0b21pY19ub3RpZnlfb25lX2RpcmVjdABfX3N0ZF9hdG9taWNfd2FpdF9kaXJlY3QAX19zdGRfYnVsa19zdWJtaXRfdGhyZWFkcG9vbF93b3JrAF9fc3RkX2Nsb3NlX3RocmVhZHBvb2xfd29yawBfX3N0ZF9jcmVhdGVfdGhyZWFkcG9vbF93b3JrAF9fc3RkX3BhcmFsbGVsX2FsZ29yaXRobXNfaHdfdGhyZWFkcwBfX3N0ZF9zdWJtaXRfdGhyZWFkcG9vbF93b3JrAF9fc3RkX3dhaXRfZm9yX3RocmVhZHBvb2xfd29ya19jYWxsYmFja3MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoYAAAAAAAAAAAAAAUYQAAWGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiGAAAAAAAACeYAAAAAAAALZgAAAAAAAAxmAAAAAAAADeYAAAAAAAAAAAAAAAAAAAiGAAAAAAAACeYAAAAAAAALZgAAAAAAAAxmAAAAAAAADeYAAAAAAAAAAAAAAAAAAApABDbG9zZVRocmVhZHBvb2xXb3JrAA0BQ3JlYXRlVGhyZWFkcG9vbFdvcmsAABEDR2V0U3lzdGVtSW5mbwCxBVN1Ym1pdFRocmVhZHBvb2xXb3JrAAANBldhaXRGb3JUaHJlYWRwb29sV29ya0NhbGxiYWNrcwAAAGAAAABgAAAAYAAAAGAAAABgAABLRVJORUwzMi5kbGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC5maWxlAAAAPwAAAP7/AABnAWF0b21pY19zdHViNS5jAAAAAAAAAAAEAAAAAAAAAAEAIAACAQAAAAAAAAAAAAAAAAQAAAAAAAAAAAAWAAAAFgAAAAEAIAACAQAAAAAAAAAAAAAAAAYAAAAAAAAAAAAvAAAALQAAAAEAIAACAQAAAAAAAAAAAAAAAAgAAAAAAAAAAABOAAAAOAAAAAEAIAACAQAAAAAAAAAAAAAAAAoAAAAAAAAAAABzAAAAVQAAAAEAIAACAQAAAAAAAAAAAAAAAAwAAAAAAAAAAACQAAAAhgAAAAEAIAACAQAAAAAAAAAAAAAAAA4AAAAAAAAAAACtAAAApQAAAAEAIAACAQAAAAAAAAAAAAAAABAAAAAAAAAAAADPAAAA4gAAAAEAIAACAQAAAAAAAAAAAAAAABIAAAAAAAAAAADrAAAAAQEAAAEAIAACAQAAAAAAAAAAAAAAAAAAAAAAAC50ZXh0AAAAAAAAAAEAAAADASYBAAAGAAAAAAAAAAAAAAAAAC54ZGF0YQAAAAAAAAQAAAADAWAAAAAAAAAAAAAAAAAAAAAAAC5wZGF0YQAAAAAAAAMAAAADAWwAAAAbAAAAAAAAAAAAAAAAAAAAAAAUAQAAAAAAAAIAAAADARIAAAAAAAAAAAAAAAAAAAAAAC50ZXh0AAAAMAEAAAEAAAADAC5kYXRhAAAAAAAAAAAAAAADAC5ic3MAAAAAAAAAAAAAAAADAC5pZGF0YSQ3EAEAAAYAAAADAC5pZGF0YSQ1eAAAAAYAAAADAC5pZGF0YSQ0SAAAAAYAAAADAC5pZGF0YSQ23gAAAAYAAAADAC50ZXh0AAAAOAEAAAEAAAADAC5kYXRhAAAAAAAAAAAAAAADAC5ic3MAAAAAAAAAAAAAAAADAC5pZGF0YSQ3DAEAAAYAAAADAC5pZGF0YSQ1cAAAAAYAAAADAC5pZGF0YSQ0QAAAAAYAAAADAC5pZGF0YSQ2xgAAAAYAAAADAC50ZXh0AAAAQAEAAAEAAAADAC5kYXRhAAAAAAAAAAAAAAADAC5ic3MAAAAAAAAAAAAAAAADAC5pZGF0YSQ3CAEAAAYAAAADAC5pZGF0YSQ1aAAAAAYAAAADAC5pZGF0YSQ0OAAAAAYAAAADAC5pZGF0YSQ2tgAAAAYAAAADAC50ZXh0AAAASAEAAAEAAAADAC5kYXRhAAAAAAAAAAAAAAADAC5ic3MAAAAAAAAAAAAAAAADAC5pZGF0YSQ3BAEAAAYAAAADAC5pZGF0YSQ1YAAAAAYAAAADAC5pZGF0YSQ0MAAAAAYAAAADAC5pZGF0YSQ2ngAAAAYAAAADAC50ZXh0AAAAUAEAAAEAAAADAC5kYXRhAAAAAAAAAAAAAAADAC5ic3MAAAAAAAAAAAAAAAADAC5pZGF0YSQ3AAEAAAYAAAADAC5pZGF0YSQ1WAAAAAYAAAADAC5pZGF0YSQ0KAAAAAYAAAADAC5pZGF0YSQ2iAAAAAYAAAADAC5maWxlAAAASQAAAP7/AABnAWZha2UAAAAAAAAAAAAAAAAAAGhuYW1lAAAAKAAAAAYAAAADAGZ0aHVuawAAWAAAAAYAAAADAC50ZXh0AAAAYAEAAAEAAAADAQAAAAAAAAAAAAAAAAAAAAAAAC5pZGF0YSQyAAAAAAYAAAADARQAAAADAAAAAAAAAAAAAAAAAC5pZGF0YSQ0KAAAAAYAAAADAC5pZGF0YSQ1WAAAAAYAAAADAC5maWxlAAAAUwAAAP7/AABnAWZha2UAAAAAAAAAAAAAAAAAAC50ZXh0AAAAYAEAAAEAAAADAQAAAAAAAAAAAAAAAAAAAAAAAC5pZGF0YSQ0UAAAAAYAAAADAQgAAAAAAAAAAAAAAAAAAAAAAC5pZGF0YSQ1gAAAAAYAAAADAQgAAAAAAAAAAAAAAAAAAAAAAC5pZGF0YSQ3FAEAAAYAAAADAQ0AAAAAAAAAAAAAAAAAAAAAAAAAAAAfAQAAIAAAAAIAAAACAAAAAAA+AQAAFAEAAAYAAAACAAAAAABaAQAAAAAAAAIAAAACAAAAAABpAQAAMAAAAAIAAAACAAAAAAB4AQAAAAAAAAEAAAACAAAAAACHAQAAIAAAAAIAAAACAAAAAACbAQAAOAEAAAEAIAACAAAAAACwAQAAYAEAAP//AAACAAAAAADIAQAAABAAAP//AAACAAAAAADhAQAAAAAgAP//AAACAAAAAAD7AQAABQAAAP//AAACAAAAAAAXAgAAQAAAAAIAAAACAAAAAAApAgAAQAAAAAIAAAACAAAAAAA7AgAAQAAAAAIAAAACAAAAAABLAgAAcAAAAAYAAAACAAAAAABmAgAAUAEAAAEAIAACAAAAAAB6AgAAAAAAAAUAAAACAAAAAACIAgAAIAAAAAIAAAACAAAAAACrAgAAABAAAP//AAACAAAAAADDAgAAYAAAAAYAAAACAAAAAADeAgAAQAAAAAIAAAACAAAAAADuAgAAQAAAAAIAAAACAAAAAAAAAwAAQAAAAAIAAAACAF9fZGxsX18AAAAAAP//AAACAAAAAAAQAwAAAAAAAP//AAACAAAAAAAlAwAAABAAAP//AAACAAAAAAA7AwAAQAAAAAIAAAACAAAAAABNAwAAiAAAAAYAAAACAAAAAABZAwAAIAAAAAIAAAACAAAAAAB3AwAAAAAAAAIAAAACAAAAAACEAwAAIAAAAAIAAAACAAAAAACSAwAAAAAAAAYAAAACAAAAAACsAwAAAAAAAAUAAAACAAAAAAC4AwAAQAAAAAIAAAACAAAAAADIAwAAWAAAAAYAAAACAAAAAADiAwAAQAAAAAIAAAACAAAAAAD0AwAASAEAAAEAIAACAAAAAAAJBAAAIAAAAAIAAAACAAAAAAAYBAAAAAIAAP//AAACAAAAAAArBAAAeAAAAAYAAAACAAAAAABQBAAABAAAAP//AAACAAAAAABlBAAAQAEAAAEAIAACAAAAAABzBAAAaAAAAAYAAAACAAAAAACHBAAAWAAAAAYAAAACAF9fZW5kX18AAAAAAAEAAAACAAAAAACVBAAAMAAAAAIAAAACAAAAAACjBAAAAAAAAAAAAAACAAAAAAC9BAAAIAAAAAIAAAACAAAAAADeBAAAAAAQAP//AAACAAAAAAD3BAAAQAAAAAIAAAACAAAAAAAJBQAAAwAAAP//AAACAAAAAAAXBQAAIAAAAAIAAAACAAAAAAA2BQAAAAAAAAEAAAACAAAAAABDBQAAMAEAAAEAIAACAAAAAABiBQAAAAAAAP//AAACAAAAAAB6BQAAAAAAAP//AAACAAAAAACLBQAAIAAAAAIAAAACAAAAAACdBQAAAgAAAP//AAACAAAAAAC5BQAAAAAAAP//AAACAAAAAADRBQAAIAAAAAIAAAACAAAAAADzBQAAQAAAAAIAAAACAAMGAABEbGxNYWluQ1JUU3RhcnR1cABfX3N0ZF9hdG9taWNfd2FpdF9kaXJlY3QAX19zdGRfYXRvbWljX25vdGlmeV9vbmVfZGlyZWN0AF9fc3RkX3BhcmFsbGVsX2FsZ29yaXRobXNfaHdfdGhyZWFkcwBfX3N0ZF9jcmVhdGVfdGhyZWFkcG9vbF93b3JrAF9fc3RkX3N1Ym1pdF90aHJlYWRwb29sX3dvcmsAX19zdGRfYnVsa19zdWJtaXRfdGhyZWFkcG9vbF93b3JrAF9fc3RkX2Nsb3NlX3RocmVhZHBvb2xfd29yawBfX3N0ZF93YWl0X2Zvcl90aHJlYWRwb29sX3dvcmtfY2FsbGJhY2tzAC5yZGF0YSR6enoAX19fUlVOVElNRV9QU0VVRE9fUkVMT0NfTElTVF9fAF9fbGliNjRfbGlia2VybmVsMzJfYV9pbmFtZQBfX2RhdGFfc3RhcnRfXwBfX19EVE9SX0xJU1RfXwBfX190bHNfc3RhcnRfXwBfX3J0X3BzcmVsb2NzX3N0YXJ0AFN1Ym1pdFRocmVhZHBvb2xXb3JrAF9fZGxsX2NoYXJhY3RlcmlzdGljc19fAF9fc2l6ZV9vZl9zdGFja19jb21taXRfXwBfX3NpemVfb2Zfc3RhY2tfcmVzZXJ2ZV9fAF9fbWFqb3Jfc3Vic3lzdGVtX3ZlcnNpb25fXwBfX19jcnRfeGxfc3RhcnRfXwBfX19jcnRfeGlfc3RhcnRfXwBfX19jcnRfeGlfZW5kX18AX19pbXBfU3VibWl0VGhyZWFkcG9vbFdvcmsAQ2xvc2VUaHJlYWRwb29sV29yawBfX2Jzc19zdGFydF9fAF9fX1JVTlRJTUVfUFNFVURPX1JFTE9DX0xJU1RfRU5EX18AX19zaXplX29mX2hlYXBfY29tbWl0X18AX19pbXBfQ3JlYXRlVGhyZWFkcG9vbFdvcmsAX19fY3J0X3hkX2VuZF9fAF9fX2NydF94cF9zdGFydF9fAF9fX2NydF94cF9lbmRfXwBfX21pbm9yX29zX3ZlcnNpb25fXwBfX3NlY3Rpb25fYWxpZ25tZW50X18AX19fY3J0X3hkX3N0YXJ0X18AX19JQVRfZW5kX18AX19SVU5USU1FX1BTRVVET19SRUxPQ19MSVNUX18AX19kYXRhX2VuZF9fAF9fQ1RPUl9MSVNUX18AX2hlYWRfbGliNjRfbGlia2VybmVsMzJfYQBfX2Jzc19lbmRfXwBfX19jcnRfeGNfZW5kX18AX19pbXBfQ2xvc2VUaHJlYWRwb29sV29yawBfX19jcnRfeGNfc3RhcnRfXwBDcmVhdGVUaHJlYWRwb29sV29yawBfX19DVE9SX0xJU1RfXwBfX2ZpbGVfYWxpZ25tZW50X18AX19pbXBfV2FpdEZvclRocmVhZHBvb2xXb3JrQ2FsbGJhY2tzAF9fbWFqb3Jfb3NfdmVyc2lvbl9fAEdldFN5c3RlbUluZm8AX19pbXBfR2V0U3lzdGVtSW5mbwBfX0lBVF9zdGFydF9fAF9fRFRPUl9MSVNUX18AX3BlaTM4Nl9ydW50aW1lX3JlbG9jYXRvcgBfX0RFTEFZX0lNUE9SVF9ESVJFQ1RPUllfc3RhcnRfXwBfX3NpemVfb2ZfaGVhcF9yZXNlcnZlX18AX19fY3J0X3h0X3N0YXJ0X18AX19zdWJzeXN0ZW1fXwBfX0RFTEFZX0lNUE9SVF9ESVJFQ1RPUllfZW5kX18AX19fdGxzX2VuZF9fAFdhaXRGb3JUaHJlYWRwb29sV29ya0NhbGxiYWNrcwBfX21ham9yX2ltYWdlX3ZlcnNpb25fXwBfX2xvYWRlcl9mbGFnc19fAF9fcnRfcHNyZWxvY3NfZW5kAF9fbWlub3Jfc3Vic3lzdGVtX3ZlcnNpb25fXwBfX21pbm9yX2ltYWdlX3ZlcnNpb25fXwBfX1JVTlRJTUVfUFNFVURPX1JFTE9DX0xJU1RfRU5EX18AX19fY3J0X3h0X2VuZF9fAA=="

# steam_api64.dll — stub so Steam binary runs without Steam client
STEAM_API64_B64="TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAAZIYHAKgJp2oAEAAAUAAAAPAAJiILAgIvAAIAAAAKAAAACAAAABAAAAAQAAAAAIHxAgAAAAAQAAAAAgAABAAAAAAAAAAFAAIAAAAAAACAAAAABAAA+i8AAAMAYAEAACAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAAAAQAAAAAGAAAFEBAAAAcAAAGAAAAAAAAAAAAAAAADAAAGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAudGV4dAAAAIAAAAAAEAAAAAIAAAAEAAAAAAAAAAAAAAAAAAAgAABgLnJkYXRhAABAAAAAACAAAAACAAAABgAAAAAAAAAAAAAAAAAAQAAAQC5wZGF0YQAAbAAAAAAwAAAAAgAAAAgAAAAAAAAAAAAAAAAAAEAAAEAueGRhdGEAAEgAAAAAQAAAAAIAAAAKAAAAAAAAAAAAAAAAAABAAABALmJzcwAAAAAACAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAwC5lZGF0YQAAUQEAAABgAAAAAgAAAAwAAAAAAAAAAAAAAAAAAEAAAEAuaWRhdGEAABgAAAAAcAAAAAIAAAAOAAAAAAAAAAAAAAAAAABAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFVIieVIiU0QiVUYTIlFILgBAAAAXcNVSInluAEAAABdw1VIieWQXcNVSInlkF3DVUiJ5UiJTRBIiVUYkF3DVUiJ5UiJTRBIiVUYkF3DVUiJ5bgBAAAAXcNVSInliU0QSIlVGEiNBZY/AABdw1VIieVIiU0QSI0FhT8AAF3DkJCQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAR0NDOiAoR05VKSAxNi4yLjAAAAAAAAAAAAAAAAAAAAD//////////wAAAAAAAAAA//////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAFhAAAABAAAAWEAAAIRAAAAhAAAAhEAAAKBAAABBAAAAoEAAALxAAABhAAAAvEAAAPhAAACBAAAA+EAAATRAAAChAAABNEAAAWBAAADBAAABYEAAAbBAAADhAAABsEAAAfRAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEEAgUEAwFQAQQCBQQDAVABBAIFBAMBUAEEAgUEAwFQAQQCBQQDAVABBAIFBAMBUAEEAgUEAwFQAQQCBQQDAVABBAIFBAMBUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKgJp2oAAAAAeGAAAAEAAAAIAAAACAAAAChgAABIYAAAaGAAAE0QAAAWEAAALxAAACgQAAAhEAAAPhAAAGwQAABYEAAAiGAAAJ9gAACtYAAAyWAAAN9gAADxYAAAD2EAAClhAAAAAAEAAgADAAQABQAGAAcAc3RlYW1fYXBpNjQuZGxsAFN0ZWFtQVBJX0dldEhTdGVhbVVzZXIAU3RlYW1BUElfSW5pdABTdGVhbUFQSV9SZWdpc3RlckNhbGxSZXN1bHQAU3RlYW1BUElfUnVuQ2FsbGJhY2tzAFN0ZWFtQVBJX1NodXRkb3duAFN0ZWFtQVBJX1VucmVnaXN0ZXJDYWxsUmVzdWx0AFN0ZWFtSW50ZXJuYWxfQ29udGV4dEluaXQAU3RlYW1JbnRlcm5hbF9GaW5kT3JDcmVhdGVVc2VySW50ZXJmYWNlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC5maWxlAAAAHwAAAP7/AABnAXN0ZWFtX3N0dWIuYwAAAAAAAAAAAAAEAAAAAAAAAAUAAAADAAAAAAAQAAAAAAAAAAEAIAACAQAAAAAAAAAAAAAAAAUAAAAAAAAAAAAiAAAAFgAAAAEAIAACAQAAAAAAAAAAAAAAAAcAAAAAAAAAAAAwAAAAIQAAAAEAIAACAQAAAAAAAAAAAAAAAAkAAAAAAAAAAABCAAAAKAAAAAEAIAACAQAAAAAAAAAAAAAAAAsAAAAAAAAAAABYAAAALwAAAAEAIAACAQAAAAAAAAAAAAAAAA0AAAAAAAAAAAB0AAAAPgAAAAEAIAACAQAAAAAAAAAAAAAAAA8AAAAAAAAAAACSAAAATQAAAAEAIAACAQAAAAAAAAAAAAAAABEAAAAAAAAAAACpAAAAWAAAAAEAIAACAQAAAAAAAAAAAAAAABMAAAAAAAAAAADRAAAAbAAAAAEAIAACAQAAAAAAAAAAAAAAAAAAAAAAAC50ZXh0AAAAAAAAAAEAAAADAX0AAAACAAAAAAAAAAAAAAAAAC5ic3MAAAAAAAAAAAUAAAADAQAIAAAAAAAAAAAAAAAAAAAAAC54ZGF0YQAAAAAAAAQAAAADAUgAAAAAAAAAAAAAAAAAAAAAAC5wZGF0YQAAAAAAAAMAAAADAWwAAAAbAAAAAAAAAAAAAAAAAAAAAADrAAAAAAAAAAIAAAADARIAAAAAAAAAAAAAAAAAAAAAAAAAAAD2AAAAIAAAAAIAAAACAAAAAAAVAQAAAAAAAAIAAAACAAAAAAAkAQAAMAAAAAIAAAACAAAAAAAzAQAAAAAAAAEAAAACAAAAAABCAQAAIAAAAAIAAAACAAAAAABWAQAAYAEAAP//AAACAAAAAABuAQAAABAAAP//AAACAAAAAACHAQAAAAAgAP//AAACAAAAAAChAQAABQAAAP//AAACAAAAAAC9AQAAQAAAAAIAAAACAAAAAADPAQAAQAAAAAIAAAACAAAAAADhAQAAQAAAAAIAAAACAAAAAADxAQAAAAAAAAUAAAACAAAAAAD/AQAAIAAAAAIAAAACAAAAAAAiAgAAABAAAP//AAACAAAAAAA6AgAAQAAAAAIAAAACAAAAAABKAgAAQAAAAAIAAAACAAAAAABcAgAAQAAAAAIAAAACAF9fZGxsX18AAAAAAP//AAACAAAAAABsAgAAAAAAAP//AAACAAAAAACBAgAAABAAAP//AAACAAAAAACXAgAAQAAAAAIAAAACAAAAAACpAgAAGAAAAAcAAAACAAAAAAC1AgAAIAAAAAIAAAACAAAAAADTAgAAAAAAAAIAAAACAAAAAADgAgAAIAAAAAIAAAACAAAAAADuAgAAAAgAAAUAAAACAAAAAAD6AgAAQAAAAAIAAAACAAAAAAAKAwAAQAAAAAIAAAACAAAAAAAcAwAAIAAAAAIAAAACAAAAAAArAwAAAAIAAP//AAACAAAAAAA+AwAABAAAAP//AAACAAAAAABTAwAAGAAAAAcAAAACAF9fZW5kX18AAAAAAAEAAAACAAAAAABhAwAAMAAAAAIAAAACAAAAAABvAwAAAAAAAAAAAAACAAAAAACJAwAAIAAAAAIAAAACAAAAAACqAwAAAAAQAP//AAACAAAAAADDAwAAQAAAAAIAAAACAAAAAADVAwAAAwAAAP//AAACAAAAAADjAwAAIAAAAAIAAAACAAAAAAACBAAAAAAAAAEAAAACAAAAAAAPBAAAAAAAAP//AAACAAAAAAAnBAAAAAAAAP//AAACAAAAAAA4BAAAIAAAAAIAAAACAAAAAABKBAAAAgAAAP//AAACAAAAAABmBAAAAAAAAP//AAACAAAAAAB+BAAAIAAAAAIAAAACAAAAAACgBAAAQAAAAAIAAAACALAEAABkdW1teV9pZmFjZQBEbGxNYWluQ1JUU3RhcnR1cABTdGVhbUFQSV9Jbml0AFN0ZWFtQVBJX1NodXRkb3duAFN0ZWFtQVBJX1J1bkNhbGxiYWNrcwBTdGVhbUFQSV9SZWdpc3RlckNhbGxSZXN1bHQAU3RlYW1BUElfVW5yZWdpc3RlckNhbGxSZXN1bHQAU3RlYW1BUElfR2V0SFN0ZWFtVXNlcgBTdGVhbUludGVybmFsX0ZpbmRPckNyZWF0ZVVzZXJJbnRlcmZhY2UAU3RlYW1JbnRlcm5hbF9Db250ZXh0SW5pdAAucmRhdGEkenp6AF9fX1JVTlRJTUVfUFNFVURPX1JFTE9DX0xJU1RfXwBfX2RhdGFfc3RhcnRfXwBfX19EVE9SX0xJU1RfXwBfX190bHNfc3RhcnRfXwBfX3J0X3BzcmVsb2NzX3N0YXJ0AF9fZGxsX2NoYXJhY3RlcmlzdGljc19fAF9fc2l6ZV9vZl9zdGFja19jb21taXRfXwBfX3NpemVfb2Zfc3RhY2tfcmVzZXJ2ZV9fAF9fbWFqb3Jfc3Vic3lzdGVtX3ZlcnNpb25fXwBfX19jcnRfeGxfc3RhcnRfXwBfX19jcnRfeGlfc3RhcnRfXwBfX19jcnRfeGlfZW5kX18AX19ic3Nfc3RhcnRfXwBfX19SVU5USU1FX1BTRVVET19SRUxPQ19MSVNUX0VORF9fAF9fc2l6ZV9vZl9oZWFwX2NvbW1pdF9fAF9fX2NydF94ZF9lbmRfXwBfX19jcnRfeHBfc3RhcnRfXwBfX19jcnRfeHBfZW5kX18AX19taW5vcl9vc192ZXJzaW9uX18AX19zZWN0aW9uX2FsaWdubWVudF9fAF9fX2NydF94ZF9zdGFydF9fAF9fSUFUX2VuZF9fAF9fUlVOVElNRV9QU0VVRE9fUkVMT0NfTElTVF9fAF9fZGF0YV9lbmRfXwBfX0NUT1JfTElTVF9fAF9fYnNzX2VuZF9fAF9fX2NydF94Y19lbmRfXwBfX19jcnRfeGNfc3RhcnRfXwBfX19DVE9SX0xJU1RfXwBfX2ZpbGVfYWxpZ25tZW50X18AX19tYWpvcl9vc192ZXJzaW9uX18AX19JQVRfc3RhcnRfXwBfX0RUT1JfTElTVF9fAF9wZWkzODZfcnVudGltZV9yZWxvY2F0b3IAX19ERUxBWV9JTVBPUlRfRElSRUNUT1JZX3N0YXJ0X18AX19zaXplX29mX2hlYXBfcmVzZXJ2ZV9fAF9fX2NydF94dF9zdGFydF9fAF9fc3Vic3lzdGVtX18AX19ERUxBWV9JTVBPUlRfRElSRUNUT1JZX2VuZF9fAF9fX3Rsc19lbmRfXwBfX21ham9yX2ltYWdlX3ZlcnNpb25fXwBfX2xvYWRlcl9mbGFnc19fAF9fcnRfcHNyZWxvY3NfZW5kAF9fbWlub3Jfc3Vic3lzdGVtX3ZlcnNpb25fXwBfX21pbm9yX2ltYWdlX3ZlcnNpb25fXwBfX1JVTlRJTUVfUFNFVURPX1JFTE9DX0xJU1RfRU5EX18AX19fY3J0X3h0X2VuZF9fAA=="

# ── Step 1: Prerequisites ─────────────────────────────────────────────────────
check_prerequisites() {
    step 1 "Checking prerequisites"

    # Homebrew
    if ! command -v brew &>/dev/null; then
        die "Homebrew not found. Install it from https://brew.sh then re-run."
    fi
    ok "Homebrew"

    # SteamCMD
    if ! command -v steamcmd &>/dev/null; then
        info "Installing SteamCMD via Homebrew..."
        brew install --cask --no-quarantine steamcmd
    fi
    ok "SteamCMD"

    # Game Porting Toolkit — Apple's Wine with D3DMetal (D3D11→Metal, no DXVK needed)
    GPTK_BASE="/Applications/Game Porting Toolkit.app/Contents/Resources/wine"
    WHISKY_WINE="$GPTK_BASE/bin/wine64"
    WHISKY_WINE_LIB="$GPTK_BASE/lib"

    if [[ ! -x "$WHISKY_WINE" ]]; then
        info "Installing Game Porting Toolkit via Homebrew (~1.3 GB)..."
        brew tap gcenx/wine 2>/dev/null || true
        brew install --cask --no-quarantine gcenx/wine/game-porting-toolkit
    fi
    xattr -cr "/Applications/Game Porting Toolkit.app" 2>/dev/null || true
    ok "Wine (Game Porting Toolkit)"

    # curl + unzip
    command -v curl  &>/dev/null || die "curl not found"
    command -v unzip &>/dev/null || die "unzip not found"
    ok "curl + unzip"

    mkdir -p "$INSTALL_DIR" "$GAME_DIR" "$WINE_DIR"
}

# ── Step 2: Download DF Classic ───────────────────────────────────────────────
download_df_classic() {
    step 2 "Downloading Dwarf Fortress Classic (base game data)"
    local zip="$INSTALL_DIR/df_classic.zip"

    if [[ -f "$GAME_DIR/data/init/init_default.txt" ]]; then
        ok "Already downloaded — skipping"
        return
    fi

    info "Fetching from bay12games.com (~20 MB)..."
    curl -L --progress-bar -o "$zip" "$DF_CLASSIC_URL"

    info "Extracting..."
    local tmp="$INSTALL_DIR/df_tmp"
    mkdir -p "$tmp"
    unzip -q "$zip" -d "$tmp"
    # The zip extracts to a subdirectory like df_53_16_win/
    local inner
    inner=$(find "$tmp" -maxdepth 1 -type d | tail -1)
    cp -r "$inner/." "$GAME_DIR/"
    rm -rf "$tmp" "$zip"
    xattr -cr "$GAME_DIR" 2>/dev/null || true
    ok "DF Classic extracted to $GAME_DIR"
}

# ── Step 3: Steam download ────────────────────────────────────────────────────
steam_download() {
    step 3 "Downloading Steam Premium content (graphics + audio + binary)"

    local depot_shared_path
    depot_shared_path=$(find /opt/homebrew/Caskroom/steamcmd -path "*/app_${STEAM_APP_ID}/depot_${DEPOT_SHARED}" -type d 2>/dev/null | head -1)
    local depot_win_path
    depot_win_path=$(find /opt/homebrew/Caskroom/steamcmd -path "*/app_${STEAM_APP_ID}/depot_${DEPOT_WINDOWS}" -type d 2>/dev/null | head -1)

    if [[ -n "$depot_shared_path" && -n "$depot_win_path" ]]; then
        ok "Steam depots already downloaded — skipping"
        DEPOT_SHARED_PATH="$depot_shared_path"
        DEPOT_WINDOWS_PATH="$depot_win_path"
        return
    fi

    printf "\n${BOLD}Steam login required.${NC}\n"
    printf "  Enter your Steam username (password will be prompted by SteamCMD):\n"
    printf "  If Steam Guard is enabled, you'll also be asked for a code.\n\n"
    # Strip quarantine from SteamCMD — it bundles Breakpad.framework which
    # macOS blocks before SteamCMD can even show the login prompt
    xattr -cr /opt/homebrew/Caskroom/steamcmd/ 2>/dev/null || true

    printf "Steam username: "; read -r STEAM_USER < /dev/tty

    info "Downloading shared content depot (~1 GB)..."
    # Redirect stdin from /dev/tty so SteamCMD can prompt for password + Steam Guard
    steamcmd \
        +login "$STEAM_USER" \
        +download_depot "$STEAM_APP_ID" "$DEPOT_SHARED" \
        +download_depot "$STEAM_APP_ID" "$DEPOT_WINDOWS" \
        +quit < /dev/tty

    DEPOT_SHARED_PATH=$(find /opt/homebrew/Caskroom/steamcmd -path "*/app_${STEAM_APP_ID}/depot_${DEPOT_SHARED}" -type d 2>/dev/null | head -1)
    DEPOT_WINDOWS_PATH=$(find /opt/homebrew/Caskroom/steamcmd -path "*/app_${STEAM_APP_ID}/depot_${DEPOT_WINDOWS}" -type d 2>/dev/null | head -1)

    [[ -n "$DEPOT_SHARED_PATH" ]]  || die "Shared depot not found after download"
    [[ -n "$DEPOT_WINDOWS_PATH" ]] || die "Windows depot not found after download"
    ok "Depots downloaded"
}

# ── Step 4: Wine bottle ───────────────────────────────────────────────────────
setup_wine_bottle() {
    step 4 "Setting up Wine bottle"

    if [[ -d "$WINE_DIR/drive_c" ]]; then
        ok "Wine bottle already set up — skipping"
        return
    fi

    # Create the directory structure Wine needs — skip wineboot entirely
    # (Wine auto-initialises the registry on first launch, avoiding GPTK
    # framework load and the macOS Gatekeeper quarantine popup at install time)
    info "Creating Wine directory structure..."
    local sys32="$WINE_DIR/drive_c/windows/system32"
    local wine_user="$WINE_DIR/drive_c/users/$(id -un)"
    mkdir -p "$sys32" \
             "$WINE_DIR/drive_c/windows/syswow64" \
             "$WINE_DIR/drive_c/Program Files" \
             "$WINE_DIR/drive_c/Program Files (x86)" \
             "$wine_user/AppData/Roaming/Bay 12 Games/Dwarf Fortress/prefs" \
             "$wine_user/AppData/Local" \
             "$wine_user/Desktop"

    info "Installing DXVK (D3D11→Metal)..."
    local wine_sys="$WHISKY_WINE_LIB/wine/x86_64-windows"
    for dll in d3d11.dll d3d10core.dll dxgi.dll; do
        cp "$wine_sys/$dll" "$sys32/$dll"
    done

    # no reg add needed —

    ok "Wine bottle ready at $WINE_DIR"
}

# ── Step 5: Install game files ────────────────────────────────────────────────
install_game_files() {
    step 5 "Installing Steam Premium graphics + audio"

    # Locate shared depot (might have been set in step 3)
    if [[ -z "${DEPOT_SHARED_PATH:-}" ]]; then
        DEPOT_SHARED_PATH=$(find /opt/homebrew/Caskroom/steamcmd -path "*/app_${STEAM_APP_ID}/depot_${DEPOT_SHARED}" -type d 2>/dev/null | head -1)
    fi
    if [[ -z "${DEPOT_WINDOWS_PATH:-}" ]]; then
        DEPOT_WINDOWS_PATH=$(find /opt/homebrew/Caskroom/steamcmd -path "*/app_${STEAM_APP_ID}/depot_${DEPOT_WINDOWS}" -type d 2>/dev/null | head -1)
    fi
    [[ -n "$DEPOT_SHARED_PATH" ]]  || die "Shared depot not found — re-run step 3"
    [[ -n "$DEPOT_WINDOWS_PATH" ]] || die "Windows depot not found — re-run step 3"

    # Steam Windows binary (replaces Classic binary)
    info "Installing Steam Windows binary..."
    cp "$DEPOT_WINDOWS_PATH/Dwarf Fortress.exe" "$GAME_DIR/Dwarf Fortress.exe"
    cp "$DEPOT_WINDOWS_PATH/fmod.dll"            "$GAME_DIR/fmod.dll"

    # Graphics + init defaults
    info "Installing Steam Premium graphics..."
    mkdir -p "$GAME_DIR/data/art" "$GAME_DIR/data/vanilla" \
             "$GAME_DIR/data/sound" "$GAME_DIR/data/init"
    cp -r "$DEPOT_SHARED_PATH/data/art/."     "$GAME_DIR/data/art/"
    cp -r "$DEPOT_SHARED_PATH/data/vanilla/." "$GAME_DIR/data/vanilla/"
    cp -r "$DEPOT_SHARED_PATH/data/init/."    "$GAME_DIR/data/init/"

    # Audio (1730 files)
    info "Installing Steam Premium audio..."
    cp -r "$DEPOT_SHARED_PATH/data/sound/." "$GAME_DIR/data/sound/"

    ok "Steam assets installed"
}

# ── Step 6: DLL stubs ─────────────────────────────────────────────────────────
install_dll_stubs() {
    step 6 "Installing DLL stubs"
    local sys32="$WINE_DIR/drive_c/windows/system32"
    local wine_builtin="$WHISKY_WINE_LIB/wine/x86_64-windows"

    # Decode stubs
    info "Writing msvcp140_atomic_wait.dll stub..."
    echo "$MSVCP140_B64" | base64 -d > "$GAME_DIR/msvcp140_atomic_wait.dll"
    cp "$GAME_DIR/msvcp140_atomic_wait.dll" "$sys32/msvcp140_atomic_wait.dll"
    # Replace Wine's unimplemented builtin
    cp "$GAME_DIR/msvcp140_atomic_wait.dll" "$wine_builtin/msvcp140_atomic_wait.dll"

    info "Writing steam_api64.dll stub..."
    echo "$STEAM_API64_B64" | base64 -d > "$GAME_DIR/steam_api64.dll"

    ok "DLL stubs installed"
}

# ── Step 7: DFHack ────────────────────────────────────────────────────────────
install_dfhack() {
    step 7 "Installing DFHack $DFHACK_VERSION"

    if [[ -f "$GAME_DIR/hack/dfhooks_dfhack.dll" ]]; then
        ok "DFHack already installed — skipping"
        return
    fi

    local zip="$INSTALL_DIR/dfhack.zip"
    info "Downloading DFHack..."
    curl -L --progress-bar -o "$zip" "$DFHACK_URL"

    info "Extracting..."
    unzip -q "$zip" -d "$GAME_DIR"
    rm "$zip"
    xattr -cr "$GAME_DIR" 2>/dev/null || true

    # Ensure auto-inject config exists
    [[ -f "$GAME_DIR/dfhooks_dfhack.ini" ]] || echo "hack/dfhooks_dfhack.dll" > "$GAME_DIR/dfhooks_dfhack.ini"

    ok "DFHack installed"
}

# ── Step 8: Configure game ────────────────────────────────────────────────────
configure_game() {
    step 8 "Configuring game (graphics + audio modes)"
    local music="$GAME_DIR/data/vanilla/vanilla_music/objects/music_standard.txt"

    # Patch whichever init_default.txt locations exist (Classic zip puts it in init/,
    # Steam depot puts it in data/init/ — patch both to be safe)
    patch_init() {
        [[ -f "$1" ]] || return 0
        sed -i '' \
            -e 's/\[USE_CLASSIC_ASCII:YES\]/[USE_CLASSIC_ASCII:NO]/' \
            -e 's/\[TITLE_SHOW_GRAPHICS_LOGOS:NO\]/[TITLE_SHOW_GRAPHICS_LOGOS:YES]/' \
            -e 's/\[TITLE_MUSIC:CLASSIC_TITLE_THEME\]/[TITLE_MUSIC:DWARF_FORTRESS]/' \
            "$1"
    }
    patch_init "$GAME_DIR/data/init/init_default.txt"
    patch_init "$GAME_DIR/init/init_default.txt"
    ok "init_default.txt updated"

    # Remove EXCLUSIVE_TITLE / EXCLUSIVE_MAIN overrides that force classic music
    if grep -q "CLASSIC_MAIN" "$music"; then
        # Delete the two Classic music blocks
        python3 - "$music" << 'PYEOF'
import sys, re
txt = open(sys.argv[1]).read()
# Remove blocks that force classic guitar loop over premium tracks
txt = re.sub(r'\[MUSIC:CLASSIC_TITLE\].*?\[CONTEXT:EXCLUSIVE_TITLE\]\n\n?', '', txt, flags=re.DOTALL)
txt = re.sub(r'\[MUSIC:CLASSIC_MAIN\].*?\[CONTEXT:EXCLUSIVE_MAIN\]\n\n?',  '', txt, flags=re.DOTALL)
open(sys.argv[1], 'w').write(txt)
PYEOF
        ok "Classic music overrides removed from music_standard.txt"
    else
        ok "music_standard.txt already patched"
    fi

    # User prefs in Wine bottle
    local wine_user
    wine_user=$(id -un)
    local prefs_dir="$WINE_DIR/drive_c/users/$wine_user/AppData/Roaming/Bay 12 Games/Dwarf Fortress/prefs"
    mkdir -p "$prefs_dir"
    if [[ ! -f "$prefs_dir/init.txt" ]]; then
        cat > "$prefs_dir/init.txt" << 'INITEOF'
[SOUND:YES]
[MASTER_VOLUME:255]
[MUSIC_VOLUME:255]
[AMBIENCE_VOLUME:230]
[SFX_VOLUME:204]
[WINDOWED:YES]
[WINDOWEDX:1200]
[WINDOWEDY:800]
[RESIZABLE:YES]
[USE_CLASSIC_ASCII:NO]
[PRINT_MODE:STANDARD]
[TEXTURE_PARAM:AUTO]
[TEXTURE_PARAM:AUTO]
INITEOF
        ok "User prefs created"
    else
        ok "User prefs already exist"
    fi
}

# ── Step 9: Create .app bundle ────────────────────────────────────────────────
create_app_bundle() {
    step 9 "Creating Dwarf Fortress.app"

    mkdir -p "$APP_PATH/Contents/MacOS"
    mkdir -p "$APP_PATH/Contents/Resources"

    # Launcher script
    cat > "$APP_PATH/Contents/MacOS/DwarfFortress" << LAUNCHEOF
#!/bin/bash
export HOME="$HOME"
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

WINE="$WHISKY_WINE"
WINE_LIB="$WHISKY_WINE_LIB"
GAME_DIR="$GAME_DIR"
WINE_DIR="$WINE_DIR"

export WINEPREFIX="\$WINE_DIR"
export WINEDLLOVERRIDES="d3d11=n;d3d10core=n;dxgi=n"
export DYLD_LIBRARY_PATH="\$WINE_LIB"
export WINEMSYNC=1
export WINEDEBUG="-all"
export STEAM_COMPAT_CLIENT_INSTALL_PATH=""

cd "\$GAME_DIR"
exec "\$WINE" "Dwarf Fortress.exe" >> /tmp/df_launch.log 2>&1
LAUNCHEOF
    chmod +x "$APP_PATH/Contents/MacOS/DwarfFortress"

    # Info.plist
    cat > "$APP_PATH/Contents/Info.plist" << 'PLISTEOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>DwarfFortress</string>
    <key>CFBundleIdentifier</key>
    <string>com.local.dwarffortress</string>
    <key>CFBundleName</key>
    <string>Dwarf Fortress</string>
    <key>CFBundleDisplayName</key>
    <string>Dwarf Fortress</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>LSMinimumSystemVersion</key>
    <string>12.0</string>
    <key>LSUIElement</key>
    <false/>
</dict>
</plist>
PLISTEOF

    ok "App bundle created at $APP_PATH"
}

# ── Step 10: Verify ───────────────────────────────────────────────────────────
verify_installation() {
    step 10 "Verifying installation"
    local errors=0

    # Key binaries
    for f in "Dwarf Fortress.exe" "fmod.dll" "steam_api64.dll" "msvcp140_atomic_wait.dll"; do
        if [[ -f "$GAME_DIR/$f" ]]; then
            ok "$f"
        else
            warn "MISSING: $f"; ((errors++))
        fi
    done

    # DFHack
    if [[ -f "$GAME_DIR/hack/dfhooks_dfhack.dll" ]]; then
        ok "DFHack $DFHACK_VERSION"
    else
        warn "MISSING: DFHack"; ((errors++))
    fi

    # Graphics folders
    for mod in vanilla_creatures_graphics vanilla_buildings_graphics vanilla_items_graphics                vanilla_plants_graphics vanilla_interface vanilla_environment; do
        if [[ -d "$GAME_DIR/data/vanilla/$mod" ]]; then
            ok "Graphics: $mod"
        else
            warn "MISSING graphics: $mod"; ((errors++))
        fi
    done

    # Audio
    local sound_count
    sound_count=$(find "$GAME_DIR/data/sound" -name "*.ogg" 2>/dev/null | wc -l | tr -d ' ')
    if [[ "$sound_count" -ge 1700 ]]; then
        ok "Audio: $sound_count OGG files"
    else
        warn "Audio incomplete: only $sound_count OGG files (expected ~1730)"; ((errors++))
    fi

    # Art
    local art_count
    art_count=$(find "$GAME_DIR/data/art" -name "*.png" 2>/dev/null | wc -l | tr -d ' ')
    if [[ "$art_count" -ge 20 ]]; then
        ok "Art: $art_count PNG files"
    else
        warn "Art incomplete: only $art_count PNG files"; ((errors++))
    fi

    # Wine bottle
    if [[ -f "$WINE_DIR/system.reg" ]]; then
        ok "Wine bottle"
    else
        warn "MISSING: Wine bottle"; ((errors++))
    fi

    # App bundle
    if [[ -x "$APP_PATH/Contents/MacOS/DwarfFortress" ]]; then
        ok "Dwarf Fortress.app"
    else
        warn "MISSING: .app launcher"; ((errors++))
    fi

    if [[ $errors -eq 0 ]]; then
        printf "\n${BOLD}${G}✓ All checks passed.${NC}\n"
    else
        printf "\n${Y}%d issue(s) found. Check warnings above.${NC}\n" "$errors"
    fi
}

# ── Main ──────────────────────────────────────────────────────────────────────
main() {
    printf "\n${BOLD}Dwarf Fortress — macOS Installer${NC}\n"
    printf "${C}Steam Premium · DFHack · One-click .app${NC}\n"
    printf "%s\n" "────────────────────────────────────────"
    printf "Install directory: ${BOLD}%s${NC}\n" "$INSTALL_DIR"
    printf "App location:      ${BOLD}%s${NC}\n\n" "$APP_PATH"

    check_prerequisites
    download_df_classic
    steam_download
    setup_wine_bottle
    install_game_files
    install_dll_stubs
    install_dfhack
    configure_game
    create_app_bundle
    verify_installation

    printf "\n${BOLD}${G}Done!${NC}\n"
    printf "  Double-click ${BOLD}Dwarf Fortress.app${NC} in ~/Applications to play.\n"
    printf "  Crash log: /tmp/df_launch.log\n\n"
}

main "$@"
